from rest_framework_simplejwt.views import TokenObtainPairView
from examenes.serializers import StudentTokenObtainPairSerializer

class StudentTokenObtainPairView(TokenObtainPairView):
    serializer_class = StudentTokenObtainPairSerializer
